//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Starship", Namespace="http://schemas.datacontract.org/2004/07/Space")]
    public partial class Starship : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Space.Person CaptainField;
        
        private Space.Person[] CrewField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Space.Person Captain
        {
            get
            {
                return this.CaptainField;
            }
            set
            {
                this.CaptainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Space.Person[] Crew
        {
            get
            {
                return this.CrewField;
            }
            set
            {
                this.CrewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Space")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AgeField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBlackHole")]
public interface IBlackHole
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/PullStarship", ReplyAction="http://tempuri.org/IBlackHole/PullStarshipResponse")]
    Space.Starship PullStarship(Space.Starship ship);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/PullStarship", ReplyAction="http://tempuri.org/IBlackHole/PullStarshipResponse")]
    System.Threading.Tasks.Task<Space.Starship> PullStarshipAsync(Space.Starship ship);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/UltimateAnswer", ReplyAction="http://tempuri.org/IBlackHole/UltimateAnswerResponse")]
    string UltimateAnswer();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackHole/UltimateAnswer", ReplyAction="http://tempuri.org/IBlackHole/UltimateAnswerResponse")]
    System.Threading.Tasks.Task<string> UltimateAnswerAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBlackHoleChannel : IBlackHole, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BlackHoleClient : System.ServiceModel.ClientBase<IBlackHole>, IBlackHole
{
    
    public BlackHoleClient()
    {
    }
    
    public BlackHoleClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BlackHoleClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BlackHoleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BlackHoleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Space.Starship PullStarship(Space.Starship ship)
    {
        return base.Channel.PullStarship(ship);
    }
    
    public System.Threading.Tasks.Task<Space.Starship> PullStarshipAsync(Space.Starship ship)
    {
        return base.Channel.PullStarshipAsync(ship);
    }
    
    public string UltimateAnswer()
    {
        return base.Channel.UltimateAnswer();
    }
    
    public System.Threading.Tasks.Task<string> UltimateAnswerAsync()
    {
        return base.Channel.UltimateAnswerAsync();
    }
}
