//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.MovieService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/ObjectManager.Model")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseYear {
            get {
                return this.ReleaseYearField;
            }
            set {
                if ((this.ReleaseYearField.Equals(value) != true)) {
                    this.ReleaseYearField = value;
                    this.RaisePropertyChanged("ReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieService.IService_Movie")]
    public interface IService_Movie {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/AddMovie", ReplyAction="http://tempuri.org/IService_Movie/AddMovieResponse")]
        int AddMovie(ConsoleApplication1.MovieService.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/AddMovie", ReplyAction="http://tempuri.org/IService_Movie/AddMovieResponse")]
        System.Threading.Tasks.Task<int> AddMovieAsync(ConsoleApplication1.MovieService.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/GetMovie", ReplyAction="http://tempuri.org/IService_Movie/GetMovieResponse")]
        ConsoleApplication1.MovieService.Movie GetMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/GetMovie", ReplyAction="http://tempuri.org/IService_Movie/GetMovieResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie> GetMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/UpdateMovie", ReplyAction="http://tempuri.org/IService_Movie/UpdateMovieResponse")]
        ConsoleApplication1.MovieService.Movie UpdateMovie(ConsoleApplication1.MovieService.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/UpdateMovie", ReplyAction="http://tempuri.org/IService_Movie/UpdateMovieResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie> UpdateMovieAsync(ConsoleApplication1.MovieService.Movie movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/GetAllMovies", ReplyAction="http://tempuri.org/IService_Movie/GetAllMoviesResponse")]
        ConsoleApplication1.MovieService.Movie[] GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/GetAllMovies", ReplyAction="http://tempuri.org/IService_Movie/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie[]> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/DeleteMovie", ReplyAction="http://tempuri.org/IService_Movie/DeleteMovieResponse")]
        bool DeleteMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Movie/DeleteMovie", ReplyAction="http://tempuri.org/IService_Movie/DeleteMovieResponse")]
        System.Threading.Tasks.Task<bool> DeleteMovieAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_MovieChannel : ConsoleApplication1.MovieService.IService_Movie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_MovieClient : System.ServiceModel.ClientBase<ConsoleApplication1.MovieService.IService_Movie>, ConsoleApplication1.MovieService.IService_Movie {
        
        public Service_MovieClient() {
        }
        
        public Service_MovieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_MovieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_MovieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_MovieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddMovie(ConsoleApplication1.MovieService.Movie movie) {
            return base.Channel.AddMovie(movie);
        }
        
        public System.Threading.Tasks.Task<int> AddMovieAsync(ConsoleApplication1.MovieService.Movie movie) {
            return base.Channel.AddMovieAsync(movie);
        }
        
        public ConsoleApplication1.MovieService.Movie GetMovie(int id) {
            return base.Channel.GetMovie(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie> GetMovieAsync(int id) {
            return base.Channel.GetMovieAsync(id);
        }
        
        public ConsoleApplication1.MovieService.Movie UpdateMovie(ConsoleApplication1.MovieService.Movie movie) {
            return base.Channel.UpdateMovie(movie);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie> UpdateMovieAsync(ConsoleApplication1.MovieService.Movie movie) {
            return base.Channel.UpdateMovieAsync(movie);
        }
        
        public ConsoleApplication1.MovieService.Movie[] GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.MovieService.Movie[]> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public bool DeleteMovie(int id) {
            return base.Channel.DeleteMovie(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMovieAsync(int id) {
            return base.Channel.DeleteMovieAsync(id);
        }
    }
}
